---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_DSN: Z29hcHB1c2VyOmdvYXBwcGFzc0Bwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZ29fZGI=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "go_db"
            - name: POSTGRES_USER
              value: "goappuser"
            - name: POSTGRES_PASSWORD
              value: "goapppass"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: nitace/go-lang-app:v5  # <-- Replace with your image
          ports:
            - containerPort: 4444
          env:
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_DSN
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  selector:
    app: go-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 4444
      NodePort: 30080
      
