---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_DSN: Z29hcHB1c2VyOmdvYXBwcGFzc0Bwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZ29fZGI=
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP