apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
    tier: backend
    environment: production
spec:
  replicas: 2  # Recommended for HA in production
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
        tier: backend
        environment: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4444"
        prometheus.io/path: "/healthz"
    spec:
      containers:
        - name: go-app
<<<<<<< Updated upstream
          image: nitace/go-lang-app:v5
          imagePullPolicy: IfNotPresent
=======
          image: nitace/go-lang-app:v5  
>>>>>>> Stashed changes
          ports:
            - containerPort: 4444
          env:
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_DSN
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4444
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4444
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
            timeoutSeconds: 2
      terminationGracePeriodSeconds: 30  # Graceful shutdown
      restartPolicy: Always
