apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  labels:
    app: go-app
    tier: backend
    environment: production
spec:
  type: LoadBalancer
  selector:
    app: go-app
  ports:
<<<<<<< Updated upstream
    - port: 80           # Port exposed externally
      targetPort: 4444   # Container port inside pod
      protocol: TCP
      name: http
=======
    - port: 80
      targetPort: 4444
      NodePort: 30080

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_DSN: Z29hcHB1c2VyOmdvYXBwcGFzc0Bwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZ29fZGI=
>>>>>>> Stashed changes
