apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  labels:
    app: go-app
    tier: backend
    environment: production
spec:
  type: LoadBalancer
  selector:
    app: go-app
  ports:
    - port: 80           # Port exposed externally
      targetPort: 4444   # Container port inside pod
      protocol: TCP
      name: http